version: '3.8'

services:
  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - alwafi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (placeholder - should be replaced with actual backend configuration)
  backend:
    image: alwafi-backend:latest  # Replace with actual backend image
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=AlWafiJobs;User=sa;Password=YourPassword123!;
    depends_on:
      - db
    networks:
      - alwafi-network
    restart: unless-stopped

  # Database (SQL Server)
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - alwafi-network
    restart: unless-stopped

  # Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - alwafi-network
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  alwafi-network:
    driver: bridge
